INSERT INTO TABLE_USER VALUES (1, 'jorge@gmail.com','holahola');
INSERT INTO TABLE_USER VALUES (2, 'paul@hotmail.com','spain>france');
INSERT INTO TABLE_CONTACT VALUES (1, '2022-04-13','Texto de prueba',1);
INSERT INTO TABLE_CONTACT VALUES (3, '2022-04-13','Texto de prueba 2',2);
INSERT INTO TABLE_PRODUCT VALUES (1, 'BlackBerry',299.99);
INSERT INTO TABLE_PRODUCT VALUES (2, 'WhiteBerry',249.99);
