DROP TABLE IF EXISTS TABLE_USUARIOS;
CREATE TABLE TABLE_USERS (
  ID INTEGER IDENTITY PRIMARY KEY,
  CARRITO VARCHAR(2047)
   );

DROP TABLE IF EXISTS TABLE_CONTACT;
CREATE TABLE TABLE_CONTACT(
    ID INTEGER IDENTITY PRIMARY KEY,
    FECHA DATE NOT NULL,
    BODY VARCHAR(2047) NOT NULL,
    IDUSER INTEGER NOT NULL,
    CONSTRAINT FKC FOREIGN KEY (IDUSER) REFERENCES TABLE_USERS (ID)
);